name: collab_mitra
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  firebase_analytics: ^11.3.5
  cloud_firestore: ^5.5.0
  firebase_core: ^3.8.0
  image_picker: ^1.1.2
  flutter_speed_dial: ^7.0.0
  localization: ^2.1.1
  flutter_localization: ^0.2.2
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  firebase_auth: ^5.3.3
  permission_handler: ^11.3.1
  provider: ^6.1.2
  fl_chart: ^0.69.2
  awesome_notifications: ^0.10.0
  excel: ^4.0.6
  path_provider: ^2.1.5
  flutter_launcher_icons: ^0.13.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
  - lib/gambar/
  - lib/i18n/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/kasir.png"